import { StyleSheet } from 'react-native';
import { colors, fontSize, fontWeight, radius, spacing } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgMain,
  },
  content: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  contentLarge: {
    paddingHorizontal: 14,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bgMain,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.lg,
    marginHorizontal: -spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: 54,
    paddingBottom: spacing.md,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  backButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
  },
  title: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: fontWeight.bold,
    color: colors.primaryDark,
    letterSpacing: 0,
  },
  errorBanner: {
    backgroundColor: 'rgba(222,103,103,0.14)',
    borderColor: 'rgba(222,103,103,0.35)',
    borderWidth: 1,
    borderRadius: 14,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  errorText: {
    color: colors.danger,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
  },
  filterSection: {
    marginBottom: spacing.lg,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 10,
  },
  filterChip: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    borderRadius: radius.round,
    borderWidth: 1,
    borderColor: 'rgba(20,19,19,0.08)',
    backgroundColor: '#EEF1F5',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 4,
  },
  filterChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
  },
  filterChipValue: {
    flex: 1,
    minWidth: 0,
    fontSize: fontSize.sm,
    color: colors.textPrimary,
    fontWeight: fontWeight.semibold,
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: 18,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: colors.primaryDark,
    fontWeight: fontWeight.bold,
  },
  sectionFab: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
  },
  fabIcon: {
    color: colors.textWhite,
  },
  dayList: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  dayCard: {
    width: 64,
    minHeight: 102,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: colors.bgWhite,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'space-between',
  },
  dayCardLarge: {
    width: 72,
    minHeight: 108,
  },
  dayCardActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  dayCardTime: {
    fontSize: 18,
    fontWeight: fontWeight.bold,
    color: colors.textPrimary,
    textAlign: 'center',
  },
  dayCardTimeActive: {
    color: colors.textWhite,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    alignSelf: 'center',
    backgroundColor: colors.textPlaceholder,
    marginTop: 6,
    opacity: 0.5,
  },
  dotActive: {
    backgroundColor: colors.textWhite,
    opacity: 0.9,
  },
  dayCardStatus: {
    marginTop: 6,
    fontSize: 9,
    fontWeight: fontWeight.semibold,
    textTransform: 'uppercase',
    textAlign: 'center',
    color: colors.textPlaceholder,
  },
  dayCardStatusActive: {
    color: colors.textWhite,
  },
  cardList: {
    gap: spacing.md,
  },
  bookingCard: {
    backgroundColor: colors.bgWhite,
    borderRadius: 18,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(217,217,217,0.35)',
    flexDirection: 'row',
    gap: spacing.md,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  bookingAvatarWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    overflow: 'hidden',
    backgroundColor: colors.primaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingAvatar: {
    width: '100%',
    height: '100%',
  },
  bookingAvatarFallback: {
    color: colors.primary,
  },
  bookingBody: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  bookingHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  bookingTitle: {
    flex: 1,
    fontSize: fontSize.xl,
    lineHeight: 24,
    fontWeight: fontWeight.bold,
    color: colors.textPrimary,
  },
  bookingTime: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.primaryDark,
  },
  bookingLine: {
    fontSize: fontSize.sm,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  bookingFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  statusBadge: {
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: radius.round,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: fontWeight.bold,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    width: 32,
    height: 32,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgCard,
  },
  actionButtonEdit: {
    backgroundColor: colors.primaryBg,
  },
  actionButtonDelete: {
    backgroundColor: colors.dangerBg,
  },
  emptyState: {
    backgroundColor: colors.bgWhite,
    borderRadius: 26,
    padding: spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyStateTitle: {
    fontSize: fontSize.xl,
    color: colors.textPrimary,
    fontWeight: fontWeight.semibold,
    marginTop: spacing.md,
  },
  emptyStateText: {
    fontSize: fontSize.base,
    lineHeight: 22,
    color: colors.textPlaceholder,
    textAlign: 'center',
    marginTop: 8,
  },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.bgWhite,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    paddingBottom: 28,
    maxHeight: '90%',
    width: '100%',
    alignSelf: 'center',
    maxWidth: 760,
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(20,19,19,0.12)',
    marginBottom: spacing.md,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  title: {
    fontSize: fontSize.lg,
    color: colors.textPrimary,
    fontWeight: fontWeight.bold,
    flex: 1,
    paddingRight: spacing.md,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: radius.round,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgCard,
  },
  content: {
    paddingBottom: 12,
  },
  helperText: {
    fontSize: fontSize.sm,
    color: colors.textPlaceholder,
    marginBottom: spacing.md,
    lineHeight: 20,
  },
  fieldButton: {
    marginBottom: spacing.md,
  },
  label: {
    fontSize: fontSize.sm,
    color: colors.textPrimary,
    fontWeight: fontWeight.semibold,
    marginBottom: 6,
  },
  fieldValueRow: {
    minHeight: 50,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  fieldValue: {
    flex: 1,
    fontSize: fontSize.base,
    color: colors.textPrimary,
    fontWeight: fontWeight.medium,
  },
  placeholder: {
    color: colors.textPlaceholder,
    fontWeight: fontWeight.regular,
  },
  dateTimeRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  halfField: {
    flex: 1,
  },
  input: {
    minHeight: 50,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: fontSize.base,
    color: colors.textPrimary,
  },
  textArea: {
    minHeight: 96,
    paddingTop: spacing.md,
  },
  actions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  cancelButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgCard,
  },
  cancelButtonText: {
    fontSize: fontSize.base,
    color: colors.textPrimary,
    fontWeight: fontWeight.semibold,
  },
  saveButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  saveButtonDisabled: {
    opacity: 0.55,
  },
  saveButtonText: {
    fontSize: fontSize.base,
    color: colors.textWhite,
    fontWeight: fontWeight.bold,
  },
});

export const sheetStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  sheet: {
    backgroundColor: colors.bgWhite,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    paddingBottom: 28,
    maxHeight: '78%',
    width: '100%',
    alignSelf: 'center',
    maxWidth: 760,
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(20,19,19,0.12)',
    marginBottom: spacing.md,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  title: {
    fontSize: fontSize.lg,
    color: colors.textPrimary,
    fontWeight: fontWeight.bold,
    flex: 1,
    paddingRight: spacing.md,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: radius.round,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgCard,
  },
  list: {
    paddingBottom: 8,
  },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.bgCard,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  optionActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
  },
  optionText: {
    flex: 1,
  },
  optionTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.textPrimary,
  },
  optionDescription: {
    marginTop: 2,
    fontSize: fontSize.sm,
    color: colors.textPlaceholder,
  },
  emptyText: {
    textAlign: 'center',
    color: colors.textPlaceholder,
    fontSize: fontSize.base,
    paddingVertical: spacing.xl,
  },
});
