name: Generate Release

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Descrição do que foi adicionado'
        required: true
        type: string
      branch:
        description: 'Branch para o release'
        required: true
        default: 'main'
        type: choice
        options:
          - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep -oP '"version":\s*"\K[^"]+' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          DATE=$(TZ='America/Sao_Paulo' date +'%d/%m/%Y')
          DESCRIPTION="${{ github.event.inputs.description }}"
          NEW_RELEASE="### [$VERSION] - $DATE\n#### Adicionado\n- $DESCRIPTION\n"
          sed -i "/## Histórico de versões/a \\
          \n$NEW_RELEASE" src/README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update README.md for version ${{ steps.get_version.outputs.VERSION }}"
          branch: "release/v${{ steps.get_version.outputs.VERSION }}"
          delete-branch: true
          title: "Release ${{ steps.get_version.outputs.VERSION }}"
          body: |
            ## Manual Release Update
            - **Version:** ${{ steps.get_version.outputs.VERSION }}
            - **Description:** ${{ github.event.inputs.description }}
          base: main

      - name: Create Zip file
        run: |
          zip -r pet-shop-project.zip . -x "*.git*" "node_modules*"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          DESCRIPTION="${{ github.event.inputs.description }}"
          gh release create "v$VERSION" pet-shop-project.zip \
            --title "Release $VERSION" \
            --notes "## O que há de novo?\n$DESCRIPTION" \
            --target main
